# from galaxy
- src: yatesr.timezone
# - src: reallyenglish.ntpd
- src: geerlingguy.ntp

# from github
- src: https://github.com/amasok/ansible-role-zsh.git
- src: https://github.com/amasok/ansible-role-tmux.git
  #
  ## from github with tag
  #- src: https://github.com/ANXS/mysql.git
  #  version: v1.0.3
